### ISSUE TITLE
LOLIN32 keeps resetting?

### ISSUE THREAD

**Issue by Bjoern2708** [cetrespeo/ESP32-E-Paper-Weather#10]
Hello,

I'm sorry to have to ask you for help again. But I can't figure out the problem. I wanted to build a second weather station for a friend. The code uploaded without any problems, but unfortunately nothing appears on the screen. So I looked at the serial monitor of the Arduino idea. The ESP32 shows the correct date and time, but then constantly resets itself. Could you please take a look at the .txt file? I also tried another microcontroller but I have the same problem there.

Thanks a lot

Björn

[Serial monitor.txt](https://github.com/cetrespeo/ESP32-E-Paper-Weather/files/14623093/Serial.monitor.txt)

**Comment by cetrespeo** [comment]
Hi Björn,

No worries. Always happy to help, and thanks for the serial log.

With the "0 SSIDs loaded", it is clear to me that you have no valid wifi in the internal wifi.txt. The app also tried to get the info from the hardcoded defaults, and couldn't get a single SSID PASS structure.

Did you use the new wifi declaration structure?. I changed it a few months ago as it failed with special characters and JSON.

Now is: String sWifiDefaultJson = "YourSSID1╚YourPassword1╔YourSSID2╚YourPassword2╔";    //customize YourSSID and YourPassword with those of your wifi. Allows multiple SSID and PASS in json format. To avoid conflicts with special characters and Json, I use char(200) to separate SSID and PASS, and char(201) to separate last PASS from next SSID

Did you hard-code your friend's WIFI or was it defined through the horrible internal web interface? (one day I should improve that)

Regards,

Unai

**Comment by Bjoern2708** [comment]
Hello Unai,

You're right. That was actually the problem. I downloaded the project again, but kept the old “config.h” file from my weather station. I did not noticed that you have updated the code. Many thanks for the support! Now the device works perfectly :)

Björn
