### ISSUE TITLE
darksky api key no longer allow to register, please implement OpenWeatherMap

### ISSUE THREAD

**Issue by david-ng-hk** [cetrespeo/ESP32-E-Paper-Weather#3]
Please implement OpenWeatherMap api.
as in darksky website  https://darksky.net/dev
it said:  We are no longer accepting new signups.

**Comment by cetrespeo** [comment]
Ok. I will check OWM api this weekend.

**Comment by cetrespeo** [comment]
Hi David,

I am checking OWM and they don't give precipitation measure. Originally the software was ready for OWM but I now remember I discarted it because of that.

Anyhow, I will include it back again in next rev and will upload with both data sources.

**Comment by cetrespeo** [comment]
Updated including OpenWeatherMap and Darksky APIs

Please choose API on sWeatherAPI and don't forget to update sWeatherKEY

Also remember to increase app size partition for rev 2.20
