### ISSUE TITLE
How to use with V2 of waveshare 4.2 epaper black/white/red

### ISSUE THREAD

**Issue by xsnoopy1958** [cetrespeo/ESP32-E-Paper-Weather#5]
Hi,
What I have to do using your Code for weather Station with waveshare 4.2 epaper Display black/white/Red?

I am a beginnen with esp32 using, but I am very interested in building the Weather Station.

**Comment by cetrespeo** [comment]
Hi,

I suppose you followed the guide. Where did you get stuck?

**Comment by cetrespeo** [comment]
Please check libraries.zip. 

Closed.
