### ISSUE TITLE
Seems like the temp & cloud & rain line is gone

### ISSUE THREAD

**Issue by david-ng-hk** [cetrespeo/ESP32-E-Paper-Weather#6]
I live in Hong Kong - Yau Ma Tei,
I notice in the past two weeks, the temperature line and cloud line and the rain line and its shadow in the display is missing.

I am using darksky API
forgot which revision I am using, but when it start, it show 2.08/4C1-Dec 14 2020

**Comment by david-ng-hk** [comment]
when I visit
https://api.darksky.net/forecast/
it show this

Support for the Dark Sky API ended on **March 31, 2023**, and has been replaced by Apple’s WeatherKit API. Developers can use WeatherKit in apps with iOS 16, iPadOS 16, macOS 13, tvOS 16, and watchOS 9 or higher with a platform-specific Swift API, and on any other platform with a REST API.

**Comment by cetrespeo** [comment]
Hi David,

I am sorry but Dark Sky app is no longer free.

I recommend using OpenweatherMap which is also allowed by the app and will be always open.

Unai
