### ISSUE TITLE
Temperature sensor not working

### ISSUE THREAD

**Issue by Bjoern2708** [cetrespeo/ESP32-E-Paper-Weather#9]
Hello,

I bought the optional temperature sensor DS18B20, unfortunately it does not display any values on the e-paper. I tested the sensor on another Arduino and it worked fine (with 3.3V and 5V). I connected the data line to pin 15 and installed an pull up SMD resistor between Vcc and the data line (As mentioned in the data sheet).

Vcc -> Red
GND -> Black
DATA -> Yellow

![Bild_1](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/f4159f53-adb4-491e-a575-60bd3d926fb9)

Pull-up Resistor:

![Pull-up resistor](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/139245704/e6e33fb6-9c7f-4b65-8c6b-dd0b8b5d0871)

Here is the link of the temperature sensor I bought:
https://www.reichelt.de/digital-thermometer-1-wire--0-5-c-to-92-ds-18b20-p58169.html?PROVID=2788&gclid=EAIaIQobChMI8uXags27gQMVm4ZoCR2BkQVyEAQYASABEgI4uPD_BwE

Data sheet:
[DS18B20Z-DAL.pdf](https://github.com/cetrespeo/ESP32-E-Paper-Weather/files/12683996/DS18B20Z-DAL.pdf)

Besides the temperature sensor, could you please tell me where I can change the IP location name? I couldn't find the "Custom Text" option.

Björn

**Comment by cetrespeo** [comment]
Hi,

Below a working setup with the DS18B that has been working for years now. Funny that the ESP32 has corrosion.
![20230924_190641](https://github.com/cetrespeo/ESP32-E-Paper-Weather/assets/14995096/6772b810-6d57-4b27-bff7-0356a948c657)

The IP location name is taken from Google Maps (using my google maps API account which may not have your local language) the first time you synchronize the GPS position, and stored in your Firebase folder for that GPS position under "your_Firebase/Weather/[GPS coords]/Locality". 

In case you are not using your own Firebase account and left the default Firebase parameters, it will be stored in my default database among other. I can change it for you if you PM your GPS coords and the correct name.
